### PR TITLE
Add tox and Travis CI config to test multiple Pythons

### PR DESCRIPTION
**Pull request by rouge8**
The configs come from https://github.com/Pylons/pyramid-cookiecutter-starter with minor tweaks.

Also added Trove classifiers so tools like `caniusepython3` know this package supports Python 3.

### CODE REVIEW

**Comment by rouge8** [comment]
To enable Travis, you'll probably have to login to https://travis-ci.org/ and add this repo.

**Comment by bertjwregeer** [comment]
I've enabled Travis for this repository. I think it'll build the next time this PR gets a push to it?

**Comment by rouge8** [comment]
Done! 🎉

**Comment by crooksey** [comment]
@rouge8  thanks for the PR.
@bbangert thanks for adding Travis

**Pull request merged**
