### PR TITLE
Bugfix "Select wrapper"

### PR DESCRIPTION
**Pull request by g-normand**

### CODE REVIEW

**Comment by g-normand** [comment]
it fixes https://github.com/Pylons/paginate_sqlalchemy/issues/4 if I'm right

**Comment by g-normand** [comment]
@crooksey  : does that look good to you?

**Comment by ergo** [comment]
Why do you need alias there?

**Comment by kor0p** [comment]
@ergo @crooksey Can anyone merge this? This is very helpful fix!

**Comment by Alcidauk** [comment]
Hi, can anyone package a new version with this bugfix ? Crooksey fork published 0.3.0 version two years ago https://pypi.org/project/paginate_sqlalchemy.

**Pull request merged**
